# Parsers For Flex

## Parser:
```
|  json field=scanned_bytes_breakdown_by_metering_type "Flex" as flex_data_scanned_bytes 
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| json field=scanned_bytes_breakdown_by_metering_type "Flex" as flex_data_scanned_bytes 
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "(?<data>\{[^\{]+\})" multi
| json field=data "field","dataTier","sizeInBytes","count" as collector, dataTier, bytes, count
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "(?<data>\{[^\{]+\})" multi
| json field=data "field","dataTier","sizeInBytes","count" as index, dataTier, bytes, count
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "(?<data>\{[^\{]+\})" multi
| json field=data "field","dataTier","sizeInBytes","count" as sourcecategory, dataTier, bytes, count
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<collector>[^\"]+)\"\:\{\"billedBytes\"\:(?<billedBytes>\d+)\,\"spansCount\"\:(?<spansCount>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<collector>[^\"]+)\"\:\{\"dataPoints\"\:(?<datapoints>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<field_type>[^\"]+)\"\:\{\"billedBytes\"\:(?<billedBytes>\d+)\,\"spansCount\"\:(?<spansCount>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<source>[^\"]+)\"\:\{\"billedBytes\"\:(?<billedBytes>\d+)\,\"spansCount\"\:(?<spansCount>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<source>[^\"]+)\"\:\{\"dataPoints\"\:(?<datapoints>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:\{\"billedBytes\"\:(?<billedBytes>\d+)\,\"spansCount\"\:(?<spansCount>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:\{\"dataPoints\"\:(?<datapoints>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<sourceHost>[^\"]+)\"\:\{\"billedBytes\"\:(?<billedBytes>\d+)\,\"spansCount\"\:(?<spansCount>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<sourcehost>[^\"]+)\"\:\{\"dataPoints\"\:(?<datapoints>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"(?<sourceName>[^\"]+)\"\:\{\"billedBytes\"\:(?<billedBytes>\d+)\,\"spansCount\"\:(?<spansCount>\d+)\}" multi
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value



## Parser:
```
| parse regex "\"field\":\"(?<field>.*?)\",\"dataTier\":\"(?<tier>.*?)\",\"sizeInBytes\":(?<size>.*?)," multi
| parse regex field=scanned_bytes_breakdown "\"(?<tier>[a-zA-Z]+)\" \: (?<tier_scanned_bytes>[0-9]+)" multi nodrop
```
### Use Cases:
Actual (Average) DPM Ingested, Actual (Average) Logs Data Scanned, Average Data Scanned - GB/Day, Avg Credits Consumed/day, Content items with scan volume  10x of avg daily ingest of last 30 days, Credits Consumed, Credits Consumed by Feature, Credits Consumed Over Time, Credits Consumed Over Time (Previous Month), Daily Ingest Vs Average Daily Ingest Capacity, Data Ingest Prediction, Data Scan Volume, Data Scan Volume Prediction, Data Scanned  Trend, Data Volume Outlier, DPM Ingest Capacity Utilization, Ingest - {{Unit}}, Ingest - DataPoints, Ingest {{Metricsources}}- Data Points, Ingest {{Metricsources}}- DPM, Ingest {{Tracingsources}}- Billed Bytes, Ingest {{Tracingsources}}- Billed GBytes per min, Ingest {{Unit}} per minute, Ingest DPM, Ingest Outlier of {{MetricsSources}}, Ingest Outlier of {{Tracingsources}} by {{Unit}}, Ingest Prediction of {{MetricsSources}}, Ingest Prediction of {{Tracingsources}} by {{Unit}}, Ingest Spike  of Last {{Unit}}, Ingest Spike (Last Data Point), Ingest Spike (Moving Avg), Ingest Spike (Moving Avg) of {{Unit}}, Ingest Today Vs Yesterday of {{MetricsSources}}, Ingest Today vs Yesterday of {{Tracingsources}}  by {{Unit}}, Ingest Trend of {{MetricsSources}}, Ingest Trend of {{Tracingsources}}, Ingest Volume, Ingest Volume - Default Index, Ingest Volume - GB/Day, Ingest Volume - Non-Default Index, Ingest Volume Trend, Log Data Scan Capacity Utilization, Orgs total Credits value exceeded input Credit, Orgs total data scanned in GB exceeded input GB value, Subscribed DPM Ingest Capacity, Subscribed Logs Data Scan Capacity, Top 5 {{Metricsources}}, Top 5 {{Tracingsources}} by BilledBytes, Top 5 Collectors, Top 5 Collectors by {{Unit}}, Top 5 Collectors Per Day, Top 5 Indexes (Non-Default), Top 5 Service by {{Unit}}, Top 5 Source Categories, Top 5 Source Categories by {{Unit}}, Top 5 Source Hosts, Top 5 source Hosts by {{Unit}}, Top 5 source Name by {{Unit}}, Top 5 Sources, Top 5 Sources by {{Unit}}, Top 50 Expensive Queries, Top Ingest Spikes for Top 5 Collectors Per Day, Usage Percentage of {{Metricsources}}, Usage Percentage of {{Tracingsources}}, Users whose total Credit Consumed exceeded  by input value, Users whose total data scanned (GB) exceeded  by input value


